server:
  port: 8081

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: INFO
        security: INFO
  file: spring.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456aaa
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mvc:
    static-path-pattern: /**
  segment:
    max-file-size: 500
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

file:
  save-path: E:/file/

mail:
  user: sc_3g8elr_test_OxApXf
  key: ab441d5b3b4b460316c34dd8ac15bfc7